services:
  hexagonal.api:
    image: hexagonal.api
    build:
      context: ./src
      dockerfile: ./Hexagonal.Api/Dockerfile
    tty: true
    ports:
      - "8081:8080"
    environment: 
       - ASPNETCORE_ENVIRONMENT=Homologation
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=HexagonalDb
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=1234
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dbnet
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  dbnet:
    driver: bridge
